gifts_search/config/routes.rb
Rails.application.routes.draw do
  resources :purchased_gifts
  resources :favorites
  resources :users
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gifts_search/app/models/favorite.rb
class Favorite < ApplicationRecord
end

gifts_search/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :gift_id, :memo)
    end
end

gifts_search/app/helpers/favorites_helper.rb
module FavoritesHelper
end

gifts_search/app/views/favorites/_form.html.erb
<%= form_with(model: favorite, local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :gift_id %>
    <%= form.number_field :gift_id %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gifts_search/app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

gifts_search/app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gift</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.gift_id %></td>
        <td><%= favorite.memo %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

gifts_search/app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

gifts_search/app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @favorite.gift_id %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @favorite.memo %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>