gifts_search/config/routes.rb
Rails.application.routes.draw do
  resources :purchased_gifts
  resources :favorites
  resources :users
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gifts_search/app/models/gift.rb
class Gift < ApplicationRecord
end

gifts_search/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:title, :photo, :url, :latitude, :longitude)
    end
end

gifts_search/app/helpers/gifts_helper.rb
module GiftsHelper
end

gifts_search/app/views/gifts/_form.html.erb
<%= form_with(model: gift, local: true) do |form| %>
  <% if gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gifts_search/app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

gifts_search/app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gifts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Photo</th>
      <th>Url</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.title %></td>
        <td><%= gift.photo %></td>
        <td><%= gift.url %></td>
        <td><%= gift.latitude %></td>
        <td><%= gift.longitude %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

gifts_search/app/views/gifts/new.html.erb
<h1>New Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Back', gifts_path %>

gifts_search/app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gift.title %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @gift.photo %>
</p>

<p>
  <strong>Url:</strong>
  <%= @gift.url %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @gift.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @gift.longitude %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>