gifts_search/config/routes.rb
Rails.application.routes.draw do
  resources :purchased_gifts
  resources :favorites
  resources :users
  resources :gifts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gifts_search/app/models/purchased_gift.rb
class PurchasedGift < ApplicationRecord
end

gifts_search/app/controllers/purchased_gifts_controller.rb
class PurchasedGiftsController < ApplicationController
  before_action :set_purchased_gift, only: [:show, :edit, :update, :destroy]

  # GET /purchased_gifts
  # GET /purchased_gifts.json
  def index
    @purchased_gifts = PurchasedGift.all
  end

  # GET /purchased_gifts/1
  # GET /purchased_gifts/1.json
  def show
  end

  # GET /purchased_gifts/new
  def new
    @purchased_gift = PurchasedGift.new
  end

  # GET /purchased_gifts/1/edit
  def edit
  end

  # POST /purchased_gifts
  # POST /purchased_gifts.json
  def create
    @purchased_gift = PurchasedGift.new(purchased_gift_params)

    respond_to do |format|
      if @purchased_gift.save
        format.html { redirect_to @purchased_gift, notice: 'Purchased gift was successfully created.' }
        format.json { render :show, status: :created, location: @purchased_gift }
      else
        format.html { render :new }
        format.json { render json: @purchased_gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchased_gifts/1
  # PATCH/PUT /purchased_gifts/1.json
  def update
    respond_to do |format|
      if @purchased_gift.update(purchased_gift_params)
        format.html { redirect_to @purchased_gift, notice: 'Purchased gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchased_gift }
      else
        format.html { render :edit }
        format.json { render json: @purchased_gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchased_gifts/1
  # DELETE /purchased_gifts/1.json
  def destroy
    @purchased_gift.destroy
    respond_to do |format|
      format.html { redirect_to purchased_gifts_url, notice: 'Purchased gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchased_gift
      @purchased_gift = PurchasedGift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchased_gift_params
      params.require(:purchased_gift).permit(:user_id, :gift_id, :memo)
    end
end

gifts_search/app/helpers/purchased_gifts_helper.rb
module PurchasedGiftsHelper
end

gifts_search/app/views/purchased_gifts/_form.html.erb
<%= form_with(model: purchased_gift, local: true) do |form| %>
  <% if purchased_gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchased_gift.errors.count, "error") %> prohibited this purchased_gift from being saved:</h2>

      <ul>
      <% purchased_gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :gift_id %>
    <%= form.number_field :gift_id %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gifts_search/app/views/purchased_gifts/edit.html.erb
<h1>Editing Purchased Gift</h1>

<%= render 'form', purchased_gift: @purchased_gift %>

<%= link_to 'Show', @purchased_gift %> |
<%= link_to 'Back', purchased_gifts_path %>

gifts_search/app/views/purchased_gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchased Gifts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gift</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchased_gifts.each do |purchased_gift| %>
      <tr>
        <td><%= purchased_gift.user_id %></td>
        <td><%= purchased_gift.gift_id %></td>
        <td><%= purchased_gift.memo %></td>
        <td><%= link_to 'Show', purchased_gift %></td>
        <td><%= link_to 'Edit', edit_purchased_gift_path(purchased_gift) %></td>
        <td><%= link_to 'Destroy', purchased_gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchased Gift', new_purchased_gift_path %>

gifts_search/app/views/purchased_gifts/new.html.erb
<h1>New Purchased Gift</h1>

<%= render 'form', purchased_gift: @purchased_gift %>

<%= link_to 'Back', purchased_gifts_path %>

gifts_search/app/views/purchased_gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purchased_gift.user_id %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @purchased_gift.gift_id %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @purchased_gift.memo %>
</p>

<%= link_to 'Edit', edit_purchased_gift_path(@purchased_gift) %> |
<%= link_to 'Back', purchased_gifts_path %>